"""initial payment core

Revision ID: 3fedac2b5284
Revises:
Create Date: 2026-09-18 15:16:25.553147
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fedac2b5284'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('webhook_url', sa.String(length=800), nullable=True),
    sa.Column('webhook_secret', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_table('payment_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('telegram_group_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_sender_id', sa.BigInteger(), nullable=True),
    sa.Column('merchant_alias', sa.String(length=160), nullable=True),
    sa.Column('static_khqr', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_group_id')
    )
    op.create_index(op.f('ix_payment_sources_business_id'), 'payment_sources', ['business_id'], unique=False)
    op.create_table('payment_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=180), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('base_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('paid_minor', sa.Integer(), nullable=False),
    sa.Column('excess_minor', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkout_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('history_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'external_id', name='uq_intent_business_external'),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_intent_business_idempotency')
    )
    op.create_index(op.f('ix_payment_intents_business_id'), 'payment_intents', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_source_id'), 'payment_intents', ['source_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_status'), 'payment_intents', ['status'], unique=False)
    op.create_table('source_cursors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('last_message_id', sa.String(length=128), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_cursors_source_id'), 'source_cursors', ['source_id'], unique=True)
    op.create_table('payment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_events_business_id'), 'payment_events', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_events_event_type'), 'payment_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_payment_events_intent_id'), 'payment_events', ['intent_id'], unique=False)
    op.create_table('payment_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('remark', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('offset_minor', sa.Integer(), nullable=True),
    sa.Column('payable_amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkout_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'remark', name='uq_request_source_remark')
    )
    op.create_index(op.f('ix_payment_requests_intent_id'), 'payment_requests', ['intent_id'], unique=True)
    op.create_index(op.f('ix_payment_requests_match_expires_at'), 'payment_requests', ['match_expires_at'], unique=False)
    op.create_index(op.f('ix_payment_requests_payable_amount_minor'), 'payment_requests', ['payable_amount_minor'], unique=False)
    op.create_index(op.f('ix_payment_requests_source_id'), 'payment_requests', ['source_id'], unique=False)
    op.create_table('amount_reservations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('base_amount_minor', sa.Integer(), nullable=False),
    sa.Column('payable_amount_minor', sa.Integer(), nullable=False),
    sa.Column('offset_minor', sa.Integer(), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['payment_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', name='uq_reservation_request'),
    sa.UniqueConstraint('source_id', 'currency', 'payable_amount_minor', name='uq_reservation_payable')
    )
    op.create_index(op.f('ix_amount_reservations_request_id'), 'amount_reservations', ['request_id'], unique=False)
    op.create_index(op.f('ix_amount_reservations_reserved_until'), 'amount_reservations', ['reserved_until'], unique=False)
    op.create_index(op.f('ix_amount_reservations_source_id'), 'amount_reservations', ['source_id'], unique=False)
    op.create_table('payment_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('transport_message_id', sa.String(length=128), nullable=False),
    sa.Column('trx_id', sa.String(length=128), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('quarantine_reason', sa.String(length=240), nullable=True),
    sa.Column('matched_request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_request_id'], ['payment_requests.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['payment_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'transport', 'transport_message_id', name='uq_evidence_transport_message'),
    sa.UniqueConstraint('source_id', 'trx_id', name='uq_evidence_source_trx')
    )
    op.create_index(op.f('ix_payment_evidence_business_id'), 'payment_evidence', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_evidence_received_at'), 'payment_evidence', ['received_at'], unique=False)
    op.create_index(op.f('ix_payment_evidence_remark'), 'payment_evidence', ['remark'], unique=False)
    op.create_index(op.f('ix_payment_evidence_source_id'), 'payment_evidence', ['source_id'], unique=False)
    op.create_index(op.f('ix_payment_evidence_state'), 'payment_evidence', ['state'], unique=False)
    op.create_index(op.f('ix_payment_evidence_trx_id'), 'payment_evidence', ['trx_id'], unique=False)
    op.create_table('webhook_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_outbox_event')
    )
    op.create_index(op.f('ix_webhook_outbox_business_id'), 'webhook_outbox', ['business_id'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_event_id'), 'webhook_outbox', ['event_id'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_lease_until'), 'webhook_outbox', ['lease_until'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_next_attempt_at'), 'webhook_outbox', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_webhook_outbox_status'), 'webhook_outbox', ['status'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['payment_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', name='uq_allocation_evidence')
    )
    op.create_index(op.f('ix_payment_allocations_evidence_id'), 'payment_allocations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_intent_id'), 'payment_allocations', ['intent_id'], unique=False)
    op.create_table('payment_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('claim_type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['payment_evidence.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['intent_id'], ['payment_intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_claims_business_id'), 'payment_claims', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_claims_evidence_id'), 'payment_claims', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_payment_claims_intent_id'), 'payment_claims', ['intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_claims_intent_id'), table_name='payment_claims')
    op.drop_index(op.f('ix_payment_claims_evidence_id'), table_name='payment_claims')
    op.drop_index(op.f('ix_payment_claims_business_id'), table_name='payment_claims')
    op.drop_table('payment_claims')
    op.drop_index(op.f('ix_payment_allocations_intent_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_evidence_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_webhook_outbox_status'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_next_attempt_at'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_lease_until'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_event_id'), table_name='webhook_outbox')
    op.drop_index(op.f('ix_webhook_outbox_business_id'), table_name='webhook_outbox')
    op.drop_table('webhook_outbox')
    op.drop_index(op.f('ix_payment_evidence_trx_id'), table_name='payment_evidence')
    op.drop_index(op.f('ix_payment_evidence_state'), table_name='payment_evidence')
    op.drop_index(op.f('ix_payment_evidence_source_id'), table_name='payment_evidence')
    op.drop_index(op.f('ix_payment_evidence_remark'), table_name='payment_evidence')
    op.drop_index(op.f('ix_payment_evidence_received_at'), table_name='payment_evidence')
    op.drop_index(op.f('ix_payment_evidence_business_id'), table_name='payment_evidence')
    op.drop_table('payment_evidence')
    op.drop_index(op.f('ix_amount_reservations_source_id'), table_name='amount_reservations')
    op.drop_index(op.f('ix_amount_reservations_reserved_until'), table_name='amount_reservations')
    op.drop_index(op.f('ix_amount_reservations_request_id'), table_name='amount_reservations')
    op.drop_table('amount_reservations')
    op.drop_index(op.f('ix_payment_requests_source_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_payable_amount_minor'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_match_expires_at'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_intent_id'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index(op.f('ix_payment_events_intent_id'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_event_type'), table_name='payment_events')
    op.drop_index(op.f('ix_payment_events_business_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_source_cursors_source_id'), table_name='source_cursors')
    op.drop_table('source_cursors')
    op.drop_index(op.f('ix_payment_intents_status'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_source_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_business_id'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_payment_sources_business_id'), table_name='payment_sources')
    op.drop_table('payment_sources')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
